#!/bin/bash
# For info about MAME compilation see http://docs.mamedev.org/
#
cd mame

# Checkout specific tag
git checkout mame0205

# Compile MAME in a 5-core machine
num_proc=`nproc`
echo "Using $num_proc processors"
make -j$num_proc

cd ..
