#!/bin/bash
# For info about MAME compilation see http://docs.mamedev.org/
#
cd mame

# Checkout specific tag
git checkout mame0204

# Compile MAME
num_proc=`nproc`
echo "Using $num_proc processors"
make REGENIE=1 -j$num_proc

cd ..
